import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ClipboardCheck, ArrowRight, Eye, FileText, CheckCircle2, XCircle, Clock, AlertCircle } from 'lucide-react';
import { PageHeader } from '@/components/ui/PageHeader';
import { ConcernBadge, StatusBadge } from '@/components/ui/Badges';
import { ConfidenceMeter } from '@/components/ui/ConfidenceMeter';
import { InfoBanner } from '@/components/ui/InfoBanner';
import { EmptyState } from '@/components/ui/States';
import { mockReviewItems } from '@/data/mockData';
import type { ReviewItem, SignalStatus } from '@/types';

const statusOrder: SignalStatus[] = ['action_required', 'awaiting_review', 'under_review', 'reviewed', 'dismissed'];

export function ReviewPage() {
  const [items, setItems] = useState<ReviewItem[]>(mockReviewItems);
  const [activeFilter, setActiveFilter] = useState<SignalStatus | 'all'>('all');

  const updateStatus = (signalId: string, status: SignalStatus) => {
    setItems((prev) => prev.map((item) => item.signalId === signalId ? { ...item, status } : item));
  };

  const sorted = [...items].sort((a, b) => statusOrder.indexOf(a.status) - statusOrder.indexOf(b.status));
  const filtered = activeFilter === 'all' ? sorted : sorted.filter((i) => i.status === activeFilter);

  const counts = {
    awaiting_review: items.filter((i) => i.status === 'awaiting_review').length,
    under_review: items.filter((i) => i.status === 'under_review').length,
    action_required: items.filter((i) => i.status === 'action_required').length,
    reviewed: items.filter((i) => i.status === 'reviewed').length,
    dismissed: items.filter((i) => i.status === 'dismissed').length,
  };

  const filters: { value: SignalStatus | 'all'; label: string; count: number }[] = [
    { value: 'all', label: 'All', count: items.length },
    { value: 'action_required', label: 'Action Required', count: counts.action_required },
    { value: 'awaiting_review', label: 'Awaiting Review', count: counts.awaiting_review },
    { value: 'under_review', label: 'Under Review', count: counts.under_review },
    { value: 'reviewed', label: 'Reviewed', count: counts.reviewed },
    { value: 'dismissed', label: 'Dismissed', count: counts.dismissed },
  ];

  return (
    <>
      <PageHeader
        title="Human Review"
        subtitle="Environmental experts review AI-generated signals and decide on action. AI recommends; humans decide."
        icon={<ClipboardCheck className="w-5.5 h-5.5" />}
        breadcrumbs={[{ label: 'Home', to: '/' }, { label: 'Review' }]}
      />

      {/* AI principle banner */}
      <InfoBanner type="info" title="AI recommends. Humans decide." className="mb-6">
        Every signal below was generated by AI pattern detection. Review the evidence, then choose to follow up, mark as reviewed, or dismiss.
      </InfoBanner>

      {/* Status summary */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3 mb-6">
        {filters.slice(1).map((f) => {
          const config = statusIconConfig[f.value as SignalStatus];
          const Icon = config.icon;
          return (
            <div key={f.value} className="surface p-4">
              <div className="flex items-center gap-2 mb-1">
                <Icon className={`w-4 h-4 ${config.color}`} />
                <span className="text-xs font-medium text-sand-500">{f.label}</span>
              </div>
              <p className="text-2xl font-semibold text-sand-900 tabular-nums">{f.count}</p>
            </div>
          );
        })}
      </div>

      {/* Filters */}
      <div className="flex items-center gap-2 mb-6 overflow-x-auto scrollbar-thin pb-1">
        {filters.map((f) => (
          <button
            key={f.value}
            onClick={() => setActiveFilter(f.value)}
            className={`px-3.5 py-1.5 rounded-lg text-sm font-medium whitespace-nowrap border transition-all ${
              activeFilter === f.value
                ? 'bg-aqua-700 text-white border-aqua-700'
                : 'bg-white text-sand-600 border-sand-200 hover:border-aqua-200 hover:text-aqua-700'
            }`}
          >
            {f.label} ({f.count})
          </button>
        ))}
      </div>

      {/* Review items */}
      {filtered.length > 0 ? (
        <div className="space-y-4">
          {filtered.map((item) => (
            <ReviewCard key={item.signalId} item={item} onStatusChange={updateStatus} />
          ))}
        </div>
      ) : (
        <EmptyState
          title="Nothing to review"
          message="All signals in this category have been processed."
          icon={<CheckCircle2 className="w-8 h-8" />}
        />
      )}
    </>
  );
}

const statusIconConfig: Record<SignalStatus, { icon: typeof Clock; color: string }> = {
  active: { icon: AlertCircle, color: 'text-aqua-500' },
  awaiting_review: { icon: Clock, color: 'text-amber-500' },
  under_review: { icon: Eye, color: 'text-aqua-400' },
  action_required: { icon: AlertCircle, color: 'text-error-500' },
  reviewed: { icon: CheckCircle2, color: 'text-success-500' },
  dismissed: { icon: XCircle, color: 'text-sand-400' },
};

function ReviewCard({ item, onStatusChange }: { item: ReviewItem; onStatusChange: (id: string, status: SignalStatus) => void }) {
  return (
    <div className="surface p-6">
      <div className="flex flex-col lg:flex-row gap-6">
        {/* Left: signal info */}
        <div className="flex-1">
          <div className="flex flex-wrap items-center gap-2 mb-3">
            <ConcernBadge level={item.concern} />
            <StatusBadge status={item.status} />
          </div>
          <h3 className="text-lg font-semibold text-sand-900">{item.title}</h3>
          <p className="text-sm text-sand-500 mt-0.5">{item.siteName}</p>

          <div className="mt-4 grid sm:grid-cols-3 gap-3">
            <div className="surface-soft px-3 py-2.5">
              <p className="text-xs text-sand-500">Evidence</p>
              <p className="text-sm font-medium text-sand-800">{item.observationCount} observations · {item.photoCount} photos</p>
            </div>
            <div className="surface-soft px-3 py-2.5">
              <p className="text-xs text-sand-500">Pattern</p>
              <p className="text-sm font-medium text-sand-800">{item.patternDescription}</p>
            </div>
            <div className="surface-soft px-3 py-2.5">
              <p className="text-xs text-sand-500">Confidence</p>
              <p className="text-sm font-semibold text-sand-800 tabular-nums">{item.confidence}%</p>
            </div>
          </div>

          <div className="mt-4 p-4 rounded-xl bg-aqua-50 border border-aqua-100">
            <p className="text-xs font-medium text-aqua-700 mb-1">Recommended next action</p>
            <p className="text-sm text-sand-700">{item.recommendedAction}</p>
          </div>
        </div>

        {/* Right: actions */}
        <div className="lg:w-56 flex-shrink-0 space-y-2">
          <Link to={`/signals/${item.signalId}`} className="block">
            <button className="w-full flex items-center justify-center gap-2 px-4 py-2.5 text-sm font-medium bg-aqua-700 text-white rounded-xl hover:bg-aqua-800 transition-colors">
              <Eye className="w-4 h-4" />
              Review Evidence
            </button>
          </Link>
          <button
            onClick={() => onStatusChange(item.signalId, 'under_review')}
            className="w-full flex items-center justify-center gap-2 px-4 py-2.5 text-sm font-medium bg-white text-sand-700 border border-sand-300 rounded-xl hover:bg-sand-50 transition-colors"
          >
            <FileText className="w-4 h-4" />
            Request Follow-up
          </button>
          <button
            onClick={() => onStatusChange(item.signalId, 'reviewed')}
            className="w-full flex items-center justify-center gap-2 px-4 py-2.5 text-sm font-medium bg-white text-success-700 border border-success-200 rounded-xl hover:bg-success-50 transition-colors"
          >
            <CheckCircle2 className="w-4 h-4" />
            Mark Reviewed
          </button>
          <button
            onClick={() => onStatusChange(item.signalId, 'dismissed')}
            className="w-full flex items-center justify-center gap-2 px-4 py-2.5 text-sm font-medium bg-white text-sand-500 border border-sand-200 rounded-xl hover:bg-sand-50 transition-colors"
          >
            <XCircle className="w-4 h-4" />
            Dismiss Signal
          </button>
        </div>
      </div>

      {/* Confidence meter */}
      <div className="mt-5 pt-5 border-t border-sand-100">
        <ConfidenceMeter value={item.confidence} size="sm" />
      </div>
    </div>
  );
}
